config/routes.rb
Todolist::Application.routes.draw do

  get "comments/create"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  resources :users
  resources :sessions

  resources :tasks do
    collection do
      get 'completed'
      get 'today'
      get 'search'
      patch 'unmark'
      patch 'complete'
    end
    resources :comments
  end

  root "tasks#all"
  get 'help' => "navigation#help"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :comments
	scope :completed, -> { where is_completed: true }
	scope :incomplete, -> { where is_completed: false }
	scope :search_name, ->(name) { where ["name LIKE ?", "%#{name}%"] }
	scope :ids, ->(ids) { where id: ids }
	scope :due_today, -> { where due_date: Date.today }
	scope :owner, ->(user_id) { where user_id: user_id }
	validates :name, :due_date, :category, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tasks
  has_many :comments
  #validates_uniqueness_of :email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
 
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize
  def create
    @task = Task.find(params[:task_id])
    @comment = current_user.comments.build(comment_params)
    @comment.task = @task
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @task, notice: 'Yes. Totally. People care about your opinions. Wew.' }
        #format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        #format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
    
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to tasks_url, notice: "My son! You have returned!"
    else
      flash.now.alert = "Mali yan. Fix yourself."
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "FINE! Corny naman tasks mo! >:P"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:all]
  # GET /tasks
  # GET /tasks.json
  def all
    @tasks = Task.all.order(due_date: :asc, name: :asc)
  end
  def index
    @tasks = task_model.incomplete.order(due_date: :asc, name: :asc)
  end

  def search
    @tasks = task_model.search_name(params[:search])
  end
  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comments = @task.comments
    @comment = @task.comments.build
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)
    @task.is_completed = false;
    
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'You can do it!' }
        #format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        #format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to @task, notice: 'GAWIN MO NA' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
  end

  def complete
      if Task.ids(params[:task_ids]).update_all(is_completed: true) 
        redirect_to completed_tasks_path  
      else
        redirect_to tasks_path
      end
  end

  def unmark
      if Task.where.not(id: params[:task_ids]).update_all(is_completed: false) 
        redirect_to tasks_path  
      else
        redirect_to completed_tasks_path
      end
  end

  def completed
    @tasks = task_model.completed.order(due_date: :asc, name: :asc)
  end
  # DELETE /tasks/1
  # DELETE /tasks/1.json
  # def destroy
  #   @task.destroy
  #   respond_to do |format|
  #     format.html { redirect_to tasks_url }
  #     format.json { head :no_content }
  #   end
  # end

  def today 
    @tasks = task_model.due_today.order(name: :asc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :category, :due_date)
    end

    def task_model      
      Task.owner(current_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  def new
	    @user = User.new
	  end

	  def create
	    @user = User.new(user_params)
	    if @user.save
	      session[:user_id] = @user.id
	      redirect_to tasks_url, notice: "Welcome to my kingdom!"
	    else
	      render "new"
	    end
	  end

	  private 
	  def user_params
	  	params.require(:user).permit(:email, :password, :password_confirmation)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "2do_ls" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
 
  <body>
     <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1>
            <a href="/">
              2do_ls
            </a>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>
   
      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="divider"></li>
          <li><a href="/tasks">Tasks</a></li>
          <li class="divider"></li>
          <li><a href="/help">Help</a></li>
          <li class="divider"></li>
          <% if current_user %>
            <li><a href=""><%= current_user.email %></a></li>
            <li class="divider"></li>
            <li><%= link_to "Goodbye", logout_path %></li>
          <% else %>
            <li><%= link_to "Join My Kingdom", signup_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
          <li class="divider"></li>
        </ul>
      </section>
    </nav>
    
  <section id="wrap" role="document">
    <div class="row">
      <div class="large-12 columns">
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div data-alert class="alert-box radius <%= name == :notice ? "success" : "alert" %>">
              <%= content_tag :div, msg %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </section>
  <footer id="footer">
    <hr>
                      <div align="center"><p>&copy; Alonswagger de Leon & Jamiesstrong Carlo Lao 2014</p>GWAPO SI NAVARRO</div>
  </footer>
    <%= javascript_include_tag "application" %>
  </font>
  </body>
</html>

app/views/navigation/help.html.erb
<div class="row">
	<div class="large-8 columns">
		<div class="orange-circle">
			<div>
				<h3>Get Things Done Quickly</h3>
	<p>With this to do list, you can finally keep tracking of the things you've finished and the things that you have to do. Best of all, it's online, so you can access it anywhere where there's internet.</p>
			</div>
		</div>
	</div>
	<div class="large-4 columns">
		<div class="gray-circle">
			<div>
				<h5 color="#888">Gems used:</h5>
				<p>rails</p>
				<p>foundation-rails</p>
				
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-7 large-offset-5 columns">
		<div class="purple-circle float-right">
			<div>
				<h3>1. Create a task</h3>
				<p>
					Create a new task using the new task button, fill in all the details and the item will be added to the list of Pending Tasks
				</p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="large-9 columns">
		<div class="blue-circle">
			<div>
				<h3>2. Get Things Done</h3>
				<p>
					Get moving and start working, once you're done with a task, tick on the checkbox corresponing to the task, then click <a href="" class="button success radius">Mark As Complete</a>
				</p>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-8 large-offset-4 columns">
		<div class="orange-circle float-right">
			<div>
				<h3>3. Filter Things Out</h3>
				<p>
					This App helps you filter what tasks are due today, what tasks have already been completed and what tasks you need to finish by today. Just click a filter to sort them. There's even a search box to help you find a specific task.
				</p>
			</div>
		</div>
	</div>
</div>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation" data-alert data-options="animation_speed:500;" class="alert-box warning radius">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-9">
      <div class="row">
        <div class="large-3 columns">
          <!-- <label for="right-label" class="right inline">Label</label> -->
          <%= f.label :name, class: "right inline" %>
        </div>
        <div class="large-9 columns">
          <!-- <input type="text" id="right-label" placeholder="Inline Text Input"> -->
          <%= f.text_field :name, placeholder: "Task" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-9">
      <div class="row">
        <div class="large-3 columns">
          <!-- <label for="right-label" class="right inline">Label</label> -->
          <%= f.label :category, class: "right inline" %>
        </div>
        <div class="large-9 columns">
          <!-- <input type="text" id="right-label" placeholder="Inline Text Input"> -->
          <%= f.text_field :category, placeholder: "Category" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="large-9">
      <div class="row">
        <div class="large-3 columns">
          <!-- <label for="right-label" class="right inline">Label</label> -->
          <%= f.label :due_date, class: "right inline" %>
        </div>
        <div class="large-9 columns">
          <!-- <input type="text" id="right-label" placeholder="Inline Text Input"> -->
          <%= f.date_field :due_date %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="actions row">
    <div class="large-5 large-offset-2 columns">
      <%= f.submit class: "button round small" %>
    </div>
    
  </div>
<% end %>

app/views/tasks/_tasklist.html.erb
<% tasks.each do |task| %>
      <div class="row">
        <div class="large-12 columns">
          <%= check_box_tag("task_ids[]", task.id, task.is_completed) %>
          <label>
          	<%= link_to task.name, task %>           
          </label>
        </div>
        <hr/>
      </div>
    <% end %>

app/views/tasks/_tasks.html.erb
<div class="row">
  <div class="large-8 columns">
    

    <div class="row">
      <div class="large-9 columns">
        <dl class="sub-nav">
          <dt>Tasks:</dt>
          <dd class="<%= 'active' if current_page?(tasks_path) %>"><%= link_to 'Pending Tasks', tasks_path%></dd>
          <dd class="<%= 'active' if current_page?(completed_tasks_path) %>"><%= link_to 'Completed Tasks', completed_tasks_path%></dd>
          <dd class="<%= 'active' if current_page?(today_tasks_path) %>"><%= link_to 'Today\'s Tasks', today_tasks_path%></dd>
          <% if current_page?(search_tasks_path) %>
            <dd class="active"><a href="#">Search Results</a></dd>
          <% end %>
        </dl>
      </div>
      <div class="large-3 columns">
        <%= link_to 'New Task', new_task_path, class: "button raidus max-width tiny" %>
      </div>
    </div>
    
    
    <%= form_tag search_tasks_path, method: :get do %>
      <div class="row collapse">
        <div class="small-9 columns">          
          <%= text_field_tag :search, nil, placeholder: "Type in the keywords" %>
        </div>
        <div class="small-3 columns">          
          <%= submit_tag "Search", class: "button postfix" %>
        </div>
      </div>
    <% end %>
    <%= form_tag incomplete ? complete_tasks_path : unmark_tasks_path , method: :patch do %>
      <% if @tasks.count > 0 && current_user%>
        <%= render partial: 'tasklist', locals: {tasks: @tasks} %>
        <% if incomplete %>
          <%= submit_tag "I AM DONE WITH THIS SHIT", class: "button small success radius" %>        
        <% else %>
          <%= submit_tag "GOTTA DO THIS SHIT", class: "button small success radius" %>        
        <% end %>
      <% else %>
        You have nothing to do. Go buy me something.
      <% end %>
      
    <% end %>
  </div>
  <div class="large-4 columns">
    <h3>Create a New Task</h3>
    <%= form_for(Task.new) do |f| %>     

      <div class="row">
        <div class="large-12 columns">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: "Name" %>
        </div>           
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= f.label :category %>
          <%= f.text_field :category, placeholder: "Category" %>
        </div>           
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= f.label :due_date %>
          <%= f.date_field :due_date %>
        </div>           
      </div>   
      <div class="row">
        <div class="large-5 large-offset-7 columns">
          <%= f.submit class: "button round small" %>
        </div>            
      </div>
        
    <% end %>

   
  </div>
</div>

app/views/tasks/all.html.erb
<div class="row">
  <div class="large-9 columns">
    <%= form_tag complete_tasks_path, method: :patch do %>
      <% if @tasks.count > 0 %>
        <%= render partial: 'tasklist', locals: {tasks: @tasks} %>
        <% if current_user %>
          <%= submit_tag "I AM DONE WITH THIS SHIT", class: "button small success radius" %>               
        <% end %>
      <% else %>
      You are free to do as you please...you bum. Care to join me in a game of Hearthstone?
      <% end %>
      
    <% end %>
  </div>
</div>

app/views/tasks/completed.html.erb
<%= render partial: 'tasks', locals: {tasks: @tasks, incomplete: false, title: "Completed Tasks"} %>

app/views/tasks/edit.html.erb
<h1><font color="red" face="Comic Sans MS">You change your mind like a girl changes clothes.</font></h1>

<%= render partial:'form', locals: {task: @task} %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= render partial: 'tasks', locals: {tasks: @tasks, incomplete: true, title: "Things To Do"} %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render partial: 'form', locals: {task: @task} %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/search.html.erb
<%= render partial: 'tasks', locals: {tasks: @tasks, incomplete: true, title: "Search Results"} %>

app/views/tasks/show.html.erb
<body background="http://autoimagesize.com/wp-content/uploads/2014/01/rainbow-backgrounds-colour-photo-rainbow-background.jpg">
<div class="row">
	<div class="large-2 columns">
		<div class="gray-circle">
			<div class="fill">				
				<p>
					<%= link_to 'Back', tasks_path %>	
				</p>				
				
			</div>
		</div>
	</div>
	<div class="large-8 columns">
		<div class="orange-circle">
			<div class="fill">
				<h3><font color="00FF00">Name:</font></h3>
	<p><%= @task.name %></p>
			</div>
		</div>
	</div>
	<div class="large-2 columns">
		<div class="gray-circle">
			<div class="fill">
				<p>
					<%= link_to 'Edit', edit_task_path(@task) %>					
				</p>								
				
			</div>
		</div>
	</div>	
</div>
<div class="row">
	<div class="large-7 large-offset-5 columns">
		<div class="purple-circle float-right">
			<div class="fill">
				<h3><font color="FFFF00">Category:</font></h3>
				<p>
					<%= @task.category %>
				</p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="large-9 columns">
		<div class="blue-circle">
			<div class="fill">
				<h3><font color="FF0099">Due Date:</font></h3>
				<p>
					<%= @task.due_date %>
				</p>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-8 large-offset-4 columns">
		<div class="orange-circle float-right">
			<div class="fill">
				<h3><font color="990099">Status</font></h3>
				<p>
					<% if @task.is_completed %>
						<font face="Wingdings" size="100"><b>CJ</b></font>
					<% else %>
						<font face="Wingdings" size="100"><b>LD</b></font>
					<% end %>
				</p>
			</div>
		</div>
	</div>
</div>
<div class="row">
  <div class="large-8 columns">

    <h1><div align="center"><font color="FF9900">Ansabe?</font></div></h1>
    <%= form_for([@task, @comment]) do |f| %>
      <% if @comment.errors.any? %>
      <div id="error_explanation" data-alert data-options="animation_speed:500;" class="alert-box warning radius">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        
        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="row">
        <div class="large-9">
          <div class="row">
            <div class="large-3 columns">
              <!-- <label for="right-label" class="right inline">Label</label> -->
              <%= f.label :comment, class: "right inline" %>
            </div>
            <div class="large-9 columns">
              <!-- <input type="text" id="right-label" placeholder="Inline Text Input"> -->
              <%= f.text_area :body, placeholder: "Woh. Say my name." %>
            </div>
          </div>
        </div>
      </div>
      <div class="actions row">
        <div class="large-5 large-offset-2 columns">
          <%= f.submit class: "button round small" %>
        </div>
        
      </div>
    <% end %>
      <h3>Comments</h3>
    <% @comments.each do |comment| %>
      <div class="row">
        <div class="large-12 columns">
          <hr/>
          <h4>
            <%= comment.user %>           
          </h4>
          <p><%= comment.body %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>
</body>

app/views/tasks/today.html.erb
<%= render partial: 'tasks', locals: {tasks: @tasks, incomplete: true, title: "Tasks Due Today"} %>

app/views/users/new.html.erb
<h1><font color="red" face="Comic Sans MS">Sign Up</font></h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" data-alert data-options="animation_speed:500;" class="alert-box warning radius">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited you from signing up:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-9">
      <div class="row">
        <div class="large-3 columns">
          <!-- <label for="right-label" class="right inline">Label</label> -->
          <%= f.label :email, class: "right inline" %>
        </div>
        <div class="large-9 columns">
          <!-- <input type="text" id="right-label" placeholder="Inline Text Input"> -->
          <%= f.text_field :email%>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-9">
      <div class="row">
        <div class="large-3 columns">
          <!-- <label for="right-label" class="right inline">Label</label> -->
          <%= f.label :password, class: "right inline" %>
        </div>
        <div class="large-9 columns">
          <!-- <input type="text" id="right-label" placeholder="Inline Text Input"> -->
          <%= f.password_field :password %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="large-9">
      <div class="row">
        <div class="large-3 columns">
          <!-- <label for="right-label" class="right inline">Label</label> -->
          <%= f.label :password_confirmation, class: "right inline" %>
        </div>
        <div class="large-9 columns">
          <!-- <input type="text" id="right-label" placeholder="Inline Text Input"> -->
          <%= f.password_field :password_confirmation %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="actions row">
    <div class="large-5 large-offset-2 columns">
      <%= f.submit "Sign Up", class: "button round small" %>
    </div>
    
  </div>
<% end %>